# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

#############################
# ENVIRONMENT VARIABLES
#############################

source = ~/.config/hypr/conf/env_vars.conf

###################
# APP DEFINITIONS
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = ghostty
$fileManager = dolphin
$menu = rofi -show combi -modes combi -combi-modes "window,drun,run" -show-icons

#################
# AUTOSTART 
#################

source = ~/.config/hypr/conf/autostart.conf

#####################
# LOOK AND FEEL
#####################

# Monitors
# Using Kanshi to manage monitor setups instead
# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto

# General (gaps, border, layout)
source = ~/.config/hypr/conf/general.conf

# Decoration
source = ~/.config/hypr/conf/decoration.conf

# Animations
source = ~/.config/hypr/conf/animations.conf

# Layout 
source = ~/.config/hypr/conf/layout.conf

# Windows and workspaces
source = ~/.config/hypr/conf/window_rules.conf

#############
# INPUT
#############

source = ~/.config/hypr/conf/input.conf

##############################
# KEYBINDINGS 
##############################

source = ~/.config/hypr/conf/keybindings.conf

##############################
# SCREENSHARE
##############################

source = ~/.config/hypr/conf/screenshare.conf
