# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Wallpaper
exec-once = hyprpaper

# Tray etc. bar
exec-once = waybar

# Bluetooth agent that actually works
exec-once = blueman-applet

# 
exec-once = systemctl --user start hyprpolkitagent

# Auto-switch display profiles based on connected monitors
exec-once = kanshi

# Idle management daemon
exec-once = hypridle

# Startup app stack
exec-once = slack
exec-once = google-chrome-stable
